name: 'Render to Deploy via CI'
description:
  'Deploy your applications to Render.com with automated status tracking and
  GitHub integration'
author: 'Russ Dias'

branding:
  icon: 'cloud'
  color: 'red'

inputs:
  RENDER_API_KEY:
    description:
      'Your Render API key from dashboard.render.com/settings/api-keys'
    required: true
  RENDER_SERVICE_ID:
    description:
      'The ID of your Render service (found in service URL or settings)'
    required: true
  GH_TOKEN:
    description:
      'GitHub token for enhanced functionality like deployment comments and
      status updates'
    required: false
    default: ${{ github.token }}

outputs:
  status:
    description:
      'The deployment status. Values: created, build_in_progress,
      update_in_progress, live, deactivated, build_failed, update_failed,
      canceled, pre_deploy_in_progress, pre_deploy_failed'

runs:
  using: node20
  main: dist/index.js
